2021-01-29 03:10:04,029 NanoPlot 1.32.1 started with arguments Namespace(N50=False, alength=False, bam=['sub1_full.sorted.bam'], barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=10000, minlength=None, minqual=None, no_N50=False, no_supplementary=False, outdir='null/', path='null/sub1_full.sorted-', percentqual=False, pickle=None, plots=['hex', 'dot', 'kde', 'pauvre'], prefix='sub1_full.sorted-', raw=True, readtype='1D', runtime_until=None, store=True, summary=None, threads=40, title='sub1_full.sorted.bam', tsv_stats=False, ubam=None, verbose=False)
2021-01-29 03:10:04,029 Python version is: 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49)  [GCC 7.5.0]
2021-01-29 03:10:04,029 NanoPlot:  valid output format png
2021-01-29 03:10:04,038 Nanoget: Starting to collect statistics from bam file sub1_full.sorted.bam.
2021-01-29 03:10:04,104 Nanoget: No index for bam file could be found, created index.
2021-01-29 03:10:04,104 Nanoget: Bam file sub1_full.sorted.bam contains 1388 mapped and 3622 unmapped reads.
2021-01-29 03:10:04,411 Nanoget: bam sub1_full.sorted.bam contains 1388 primary alignments.
2021-01-29 03:10:04,428 Reduced DataFrame memory usage from 0.19723129272460938Mb to 0.15619659423828125Mb
2021-01-29 03:10:04,442 Nanoget: Gathered all metrics of 1388 reads
2021-01-29 03:10:04,480 Calculated statistics
2021-01-29 03:10:04,481 Using sequenced read lengths for plotting.
2021-01-29 03:10:04,483 Hidding 0 reads longer than 10000bp in length plots.
2021-01-29 03:10:04,486 NanoPlot:  Valid color #4CB391.
2021-01-29 03:10:04,487 NanoPlot:  Valid colormap Greens.
2021-01-29 03:10:04,488 NanoPlot:  Creating length plots for Read length.
2021-01-29 03:10:04,488 NanoPlot:  Using 1388 reads maximum of 3219bp.
2021-01-29 03:10:05,836 Nanoplotter: orca not found, not creating static image of html. See https://github.com/plotly/orca
2021-01-29 03:10:05,836 Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nanoplotter/plot.py", line 60, in save_static
    pio.write_image(self.fig, self.path.replace('html', 'png'))
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 244, in write_image
    img_data = to_image(
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 102, in to_image
    return to_image_orca(
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1535, in to_image
    ensure_server()
  File "/usr/local/lib/python3.8/site-packages/plotly/io/_orca.py", line 1361, in ensure_server
    raise ValueError(
ValueError: Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil

2021-01-29 03:10:06,033 Created length plots
2021-01-29 03:10:06,035 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 1388 reads.
2021-01-29 03:10:09,388 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/matplotlib/__init__.py", line 677, in __setitem__
    cval = self.validate[key](val)
KeyError: 'text.latex.unicode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 160, in make_plots
    nanoplotter.scatter(
  File "/usr/local/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 222, in scatter
    margin_plot(df=pd.DataFrame({"length": x, "meanQual": y}),
  File "/usr/local/lib/python3.8/site-packages/pauvre/marginplot.py", line 197, in margin_plot
    rc.update_rcParams()
  File "/usr/local/lib/python3.8/site-packages/pauvre/rcparams.py", line 7, in update_rcParams
    rcParams.update({
  File "/usr/local/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/usr/local/lib/python3.8/site-packages/matplotlib/__init__.py", line 682, in __setitem__
    raise KeyError(
KeyError: 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'
