[WARNING]         multiqc : MultiQC Version v1.9 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /scratch/bhargava/nextflow-test/work/6d/f35373165e00ef5cfe63625b17ea7a
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 7, in <module>
    from multiqc.__main__ import multiqc
  File "/usr/local/lib/python3.5/dist-packages/multiqc/__main__.py", line 44, in <module>
    multiqc.run_cli(prog_name='multiqc')
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multiqc/multiqc.py", line 238, in run_cli
    kwargs=kwargs
  File "/usr/local/lib/python3.5/dist-packages/multiqc/multiqc.py", line 517, in run
    template_mod = config.avail_templates[config.template].load()
  File "/home/bhargavam/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/bhargavam/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/bhargavam/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyYAML 3.13 (/home/bhargavam/.local/lib/python3.5/site-packages), Requirement.parse('pyyaml>=4'))
